run:
  timeout: 5m
  tests: true

linters:
  enable-all: true
  disable:
    - execinquery
    - exportloopref
    - gomnd
    - depguard
    - tagliatelle
    - varnamelen
    - dupl
    - errcheck
    - exhaustruct
    - funlen
    - gci
  fast: false

issues:
  include:
    - EXC0001 
    - EXC0004 
    - EXC0005 

  exclude-rules:
    - linters:
        - ireturn
      text: "returns generic interface"
    - linters:
        - revive
      text: "unexported-return: exported func .+ returns unexported type .+, which can be annoying to use"

linters-settings:
  revive:
    rules:
      - name: duplicated-imports
        severity: error
  cyclop:
    max-complexity: 12