// Code generated by mockery. DO NOT EDIT.

package wifi_test

import (
	wifi "github.com/mdlayher/wifi"
	mock "github.com/stretchr/testify/mock"
)

type WiFiHandle struct {
	mock.Mock
}

func (_m *WiFiHandle) Interfaces() ([]*wifi.Interface, error) {
	ret := _m.Called()

	var r0 []*wifi.Interface
	var r1 error

	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]*wifi.Interface)
	}
	r1 = ret.Error(1)

	return r0, r1
}

func NewWiFiHandle(t mock.TestingT) *WiFiHandle {
	m := &WiFiHandle{}
	m.Mock.Test(t)
	return m
}
